# Generated by Django 6.0.1 on 2026-01-27 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('distance_to_transport', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bills', models.CharField(choices=[('included', 'Included'), ('not_included', 'Not Included'), ('partial', 'Partially Included')], max_length=20)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('ensuite', 'Ensuite Room'), ('studio', 'Studio'), ('shared', 'Shared Room')], max_length=20)),
                ('furnished', models.CharField(choices=[('fully', 'Fully Furnished'), ('part', 'Part Furnished'), ('unfurnished', 'Unfurnished')], max_length=20)),
                ('available_from', models.DateField()),
                ('min_stay_months', models.IntegerField(default=6)),
                ('max_stay_months', models.IntegerField(default=12)),
                ('image_1', models.URLField(max_length=500)),
                ('image_2', models.URLField(blank=True, max_length=500)),
                ('image_3', models.URLField(blank=True, max_length=500)),
                ('image_4', models.URLField(blank=True, max_length=500)),
                ('image_5', models.URLField(blank=True, max_length=500)),
                ('wifi', models.BooleanField(default=False)),
                ('washing_machine', models.BooleanField(default=False)),
                ('dishwasher', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('central_heating', models.BooleanField(default=False)),
                ('double_glazing', models.BooleanField(default=False)),
                ('security_system', models.BooleanField(default=False)),
                ('bike_storage', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accounts.student')),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['-created_at'],
            },
        ),
    ]
