# Generated by Django 6.0.1 on 2026-01-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_is_online_student_last_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image_1',
            field=models.ImageField(max_length=500, upload_to='room_images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image_2',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='room_images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image_3',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='room_images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image_4',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='room_images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image_5',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='room_images/'),
        ),
    ]
