# Generated by Django 6.0.1 on 2026-02-01 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('scam', 'Scam/Fraudulent Listing'), ('incorrect', 'Incorrect Information'), ('inappropriate', 'Inappropriate Content'), ('duplicate', 'Duplicate Listing'), ('unavailable', 'Property No Longer Available'), ('discrimination', 'Discriminatory Content'), ('safety', 'Safety Concerns'), ('other', 'Other Issue')], max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to='accounts.student')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.room')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='reports_status_d7deb7_idx'), models.Index(fields=['reporter', '-created_at'], name='reports_reporte_25ecfc_idx'), models.Index(fields=['room', '-created_at'], name='reports_room_id_e2d0bf_idx')],
            },
        ),
    ]
